name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Set Firebase project ID
        env:
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        run: firebase use $FIREBASE_PROJECTID
      - name: Deploy to firebase hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
